// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bodyKey: __t.u64().primaryKey().name("body_key"),
  worldKey: __t.u64().name("world_key"),
  px: __t.f32(),
  py: __t.f32(),
  pz: __t.f32(),
  qx: __t.f32(),
  qy: __t.f32(),
  qz: __t.f32(),
  qw: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  wx: __t.f32(),
  wy: __t.f32(),
  wz: __t.f32(),
  asleep: __t.bool(),
});
