// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const B3BodyRow = __t.object("B3BodyRow", {
  bodyKey: __t.u64(),
  worldKey: __t.u64(),
  px: __t.f32(),
  py: __t.f32(),
  pz: __t.f32(),
  qx: __t.f32(),
  qy: __t.f32(),
  qz: __t.f32(),
  qw: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  wx: __t.f32(),
  wy: __t.f32(),
  wz: __t.f32(),
  asleep: __t.bool(),
});
export type B3BodyRow = __Infer<typeof B3BodyRow>;

export const B3WorldRow = __t.object("B3WorldRow", {
  worldKey: __t.u64(),
  generation: __t.u64(),
  tick: __t.u64(),
  lastStepAtMicros: __t.i64(),
  ephemeral: __t.bool(),
  gx: __t.f32(),
  gy: __t.f32(),
  gz: __t.f32(),
  capStaticShapeCount: __t.i32(),
  capDynamicShapeCount: __t.i32(),
  capStaticBodyCount: __t.i32(),
  capDynamicBodyCount: __t.i32(),
  capContactCount: __t.i32(),
});
export type B3WorldRow = __Infer<typeof B3WorldRow>;

export const BodyKeyGen = __t.object("BodyKeyGen", {
  id: __t.u8(),
  next: __t.u64(),
});
export type BodyKeyGen = __Infer<typeof BodyKeyGen>;

export const Connected = __t.object("Connected", {
  connection: __t.connectionId(),
});
export type Connected = __Infer<typeof Connected>;

export const GameBody = __t.object("GameBody", {
  bodyKey: __t.u64(),
  kind: __t.u8(),
  half: __t.f32(),
});
export type GameBody = __Infer<typeof GameBody>;

export const PendingDespawn = __t.object("PendingDespawn", {
  bodyKey: __t.u64(),
});
export type PendingDespawn = __Infer<typeof PendingDespawn>;

export const Score = __t.object("Score", {
  id: __t.u8(),
  pitCount: __t.u64(),
});
export type Score = __Infer<typeof Score>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const Tuning = __t.object("Tuning", {
  id: __t.u8(),
  shootImpulse: __t.f32(),
  launchSpeed: __t.f32(),
});
export type Tuning = __Infer<typeof Tuning>;

